### ISSUE TITLE
Filetype not allowed

### ISSUE THREAD

**Issue by nicolasagustinrinaldi** [ticgal/gdrive#13]
I get the following error when selecting any file from GDrive that is Gdoc, Gsheet or Gslide. PDFs work fine for example:

![image](https://user-images.githubusercontent.com/63612082/142374726-a4f9b8b2-0e3b-4960-9175-5f315fbd1c8d.png)

This is related to the filetype extension. Since these are Google files, they don't have an extension, which makes it imposible to upload.

Any idea on how to fix this?

Thanks!

**Comment by OscarBeiro** [comment]
Hi,

I don't know if you can directly open in any other tool a Google Doc file. Maybe you need to work on them as odt or doc.

I'm afraid there's nothing we can do on our side.

Regards,
