### ISSUE TITLE
Error idpiframe_initialization_failed al intentar usar el plugin

### ISSUE THREAD

**Issue by ftoledo** [ticgal/gdrive#15]
Instalé y configuré el plugin según los pasos indicados. Creado el proyecto, las keys etc..
Nuestro sitio esta vía http, pero al abrir el popoup con la sección se las cuentas de google. Aparce otro popup por detras con el siguiente error:

idpiframe_initialization_failed

Alguna idea de que puede estar fallando?

dejo unas capturas:

![imagen](https://user-images.githubusercontent.com/95441/184003704-65e16c49-f184-42bf-9c28-664e4f4e7766.png)

![imagen](https://user-images.githubusercontent.com/95441/184003771-3999b096-53b1-4f30-94f1-2925a3274c4d.png)

![imagen](https://user-images.githubusercontent.com/95441/184003738-92125754-63f0-4ca2-aca6-d1a5e0575fb3.png)

**Comment by OscarBeiro** [comment]
Si no me equivoco sólo https está soportado por Google.
Saludos.
