### ISSUE TITLE
Enable GDrive in assets

### ISSUE THREAD

**Issue by OscarBeiro** [ticgal/gdrive#5]
Allow assets to add documents from Google Drive

**Comment by obarriospino** [comment]
Saludos. Para cuál versión  de GLPI está disponible este plugin?

**Comment by xacobofg** [comment]
> Saludos. Para cuál versión de GLPI está disponible este plugin?

Se probo su correcto funcionamiento en las versiones 9.2 y 9.3.0 de GLPI

**Comment by obarriospino** [comment]
> > Saludos. Para cuál versión de GLPI está disponible este plugin?
> 
> Se probo su correcto funcionamiento en las versiones 9.2 y 9.3.0 de GLPI

han considerado habilitarlo para la versión 9.1?

**Comment by OscarBeiro** [comment]
Contestada en @ #10

**Comment by juanfvilla** [comment]
Lo pueden habilitar para la versión 9.5? Aparece un error

**Comment by OscarBeiro** [comment]
@juanfvilla ¿Que error? 
Si no está relacionado con este ticket, por favor abre otro issue. Si es posible en inglés.
Gracias.

**Comment by OscarBeiro** [comment]
Dealing with it on #16
